spring.application.name=inventario
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario
spring.datasource.password=inventario_123

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true
