spring.application.name=inventario
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario
spring.datasource.username=postgres
spring.datasource.password=inventario_123

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:schema.sql
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
